// Zero-dependency build: concatenates the content-script bundle and copies
// per-browser manifests into dist/chrome and dist/firefox.
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const SRC = path.join(__dirname, 'src');
const DIST = path.join(__dirname, 'dist');

// Order matters: libs first, entry point last.
const CONTENT_FILES = [
  'lib/css-filter.js',
  'lib/css-to-scss.js',
  'lib/css-to-tailwind.js',
  'content/inspector.js',
  'content/panel.js',
  'content/content-script.js',
];

function buildContentBundle() {
  const parts = CONTENT_FILES.map((f) => {
    const code = fs.readFileSync(path.join(SRC, f), 'utf8');
    return `// ---- src/${f} ----\n${code}`;
  });
  return (
    '// Generated by build.js — do not edit directly.\n' +
    '(() => {\n' +
    "  if (globalThis.__cssInspectorInjected) return;\n" +
    '  globalThis.__cssInspectorInjected = true;\n\n' +
    parts.join('\n') +
    '\n})();\n'
  );
}

function buildTarget(name, manifestFile) {
  const dir = path.join(DIST, name);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'content.js'), buildContentBundle());
  fs.copyFileSync(path.join(SRC, 'background.js'), path.join(dir, 'background.js'));
  fs.copyFileSync(path.join(SRC, manifestFile), path.join(dir, 'manifest.json'));
  console.log(`built dist/${name}`);
}

buildTarget('chrome', 'manifest.chrome.json');
buildTarget('firefox', 'manifest.firefox.json');
